In [ ]:
subjects = ["Python", "Math", "AI", "Data"]

In [ ]:
print(subjects)
print(subjects[0])
print(subjects[len(subjects)-1])

['Python', 'Math', 'AI', 'Data']
Python
Data


In [ ]:
college={"college_name":"GLA"}
college["city"]="Mathura"
college["grades"]=["A","B","C"]

In [ ]:
marks = 72

if marks>=40:
  print("Pass")
else:
  print("Fail")

Pass


In [ ]:
if marks >= 80:
  print("Distinction")
elif marks >=40:
  print("pass")
else:
  print("fail")

pass


In [ ]:
if marks%2 == 0:
  print("Even")
else:
  print("Odd")

Even


In [ ]:
age = int(input())
if age <=13:
  print("Child")
elif age <=19:
  print("Teenager")
else:
  print("Adult")

45
Adult


In [ ]:
students = [
    {"name": "Ansh", "grade": 85},
    {"name": "Anubhav", "grade": 60},
    {"name": "Didi", "grade": 99},
    {"name": "Hardik", "grade": 55},
    {"name": "Dev", "grade": 95}
]

for student in students:
    print("Student:", student["name"])
    print("Marks:", student["grade"])

    if student["grade"] >= 75:
        print("Performance: Strong")
    elif student["grade"] >= 50:
        print("Performance: Average")
    else:
        print("Performance: Needs Help")

Student: Ansh
Marks: 85
Performance: Strong
Student: Anubhav
Marks: 60
Performance: Average
Student: Didi
Marks: 99
Performance: Strong
Student: Hardik
Marks: 55
Performance: Average
Student: Dev
Marks: 95
Performance: Strong


In [ ]:
def Pass_or_Fail(marks):
  if marks >=40:
    print("Pass")
  else:
    print("Fail")

marks = 85
Pass_or_Fail(marks)

Pass


In [ ]:
import numpy as np
marks = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(marks)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [15]:
import numpy as np
grid= np.array([
[11, 12,13, 14, 15],
[21,22,23,24,25],
[31,32,33,34,35],
[41,42,43,44,45],
[51, 52,53,54,55]
])

print(grid[0,0])
print (grid[2,3])
print(grid[1,4])
print(grid[1,4])
print(grid[0])
print(grid[:,0])
print(grid[3,3])
grid[1:4,1:4]

11
34
25
25
[11 12 13 14 15]
[11 21 31 41 51]
44


array([[22, 23, 24],
       [32, 33, 34],
       [42, 43, 44]])

In [17]:
marks = np.array([78,91,55, 72,40,88])
print (marks>70)
high_scorers = marks[marks>70]
print(high_scorers)

[ True  True False  True False  True]
[78 91 72 88]


In [19]:
from google. colab import files
uploaded =files.upload()

Saving session4_dummy_students_data.csv.xls to session4_dummy_students_data.csv.xls


In [21]:
import pandas as pd
df = pd.read_csv("session4_dummy_students_data.csv.xls")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [22]:
print(df.head())

   student_id   name  age     city  math  science  english  \
0         101  Aarav   16   Mumbai    78       84       69   
1         102   Diya   16    Delhi    91       88       94   
2         103  Kabir   17  Mathura    55       61       58   
3         104  Meera   16    Noida    72       79       81   
4         105  Rohan   17   Mumbai    40       52       47   

   attendance_percent  study_hours_per_week  assignments_submitted  \
0                  92                     8                      9   
1                  96                    11                     10   
2                  75                     5                      6   
3                  89                     7                      8   
4                  68                     3                      5   

   final_project_score  
0                   82  
1                   93  
2                   60  
3                   78  
4                   45  


In [23]:
print(df. columns)

Index(['student_id', 'name', 'age', 'city', 'math', 'science', 'english',
       'attendance_percent', 'study_hours_per_week', 'assignments_submitted',
       'final_project_score'],
      dtype='object')


In [24]:
print(df.info)

<bound method DataFrame.info of     student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14      

In [25]:
math_marks = np.array(df['math'])
print(math_marks)

[78 91 55 72 40 88 64 95 48 83 67 74 35 89 58 92 61 80 43 77]


In [27]:
science_marks = np.array(df['science'])
print(science_marks)
print(science_marks.mean())

[84 88 61 79 52 93 70 92 57 76 63 81 45 86 54 90 69 85 49 73]


In [29]:
df["Average"] = df[["math", "science", "english"]].mean(axis=1)

print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [31]:
top_stu = df[df['Average'] > 85]
low_att = df[df['attendance_percent'] < 75]
mathura = df[df['city'] == "Mathura"]


In [32]:
print(top_stu)
print(low_att)
print(mathura)

    student_id    name  age   city  math  science  english  \
1          102    Diya   16  Delhi    91       88       94   
5          106    Sara   16  Delhi    88       93       90   
7          108  Ananya   16  Noida    95       92       89   
13         114   Priya   16  Delhi    89       86       91   
15         116    Riya   16  Noida    92       90       96   

    attendance_percent  study_hours_per_week  assignments_submitted  \
1                   96                    11                     10   
5                   97                    10                     10   
7                   94                    12                     10   
13                  95                    10                     10   
15                  98                    13                     10   

    final_project_score    Average  
1                    93  91.000000  
5                    95  90.333333  
7                    91  92.000000  
13                   92  88.666667  
15             

In [34]:
print(df['Average'].mean())

71.35000000000001


In [36]:
df['result'] = df['Average'].apply(lambda x: 'Pass' if x >= 40 else 'Fail')
print(df["result"])

0     Pass
1     Pass
2     Pass
3     Pass
4     Pass
5     Pass
6     Pass
7     Pass
8     Pass
9     Pass
10    Pass
11    Pass
12    Pass
13    Pass
14    Pass
15    Pass
16    Pass
17    Pass
18    Pass
19    Pass
Name: result, dtype: object


In [37]:
print(df['Average'].max())

92.66666666666667


In [38]:
print(df['Average'].min())

40.666666666666664


In [39]:
top_stu = df[df['Average'] > 85]
print(top_stu)

    student_id    name  age   city  math  science  english  \
1          102    Diya   16  Delhi    91       88       94   
5          106    Sara   16  Delhi    88       93       90   
7          108  Ananya   16  Noida    95       92       89   
13         114   Priya   16  Delhi    89       86       91   
15         116    Riya   16  Noida    92       90       96   

    attendance_percent  study_hours_per_week  assignments_submitted  \
1                   96                    11                     10   
5                   97                    10                     10   
7                   94                    12                     10   
13                  95                    10                     10   
15                  98                    13                     10   

    final_project_score    Average result  
1                    93  91.000000   Pass  
5                    95  90.333333   Pass  
7                    91  92.000000   Pass  
13                   92 

In [40]:
low_att = df[df['attendance_percent'] < 75]
print(low_att)

    student_id    name  age     city  math  science  english  \
4          105   Rohan   17   Mumbai    40       52       47   
8          109  Vivaan   17   Mumbai    48       57       51   
12         113     Dev   17   Mumbai    35       45       42   
18         119    Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5   
8                   71                     4                      6   
12                  62                     2                      4   
18                  66                     3                      5   

    final_project_score    Average result  
4                    45  46.333333   Pass  
8                    55  52.000000   Pass  
12                   39  40.666667   Pass  
18                   48  46.000000   Pass  


In [41]:
fewer_than_6 = df[df['assignments_submitted'] < 6]
print(fewer_than_6)

    student_id   name  age     city  math  science  english  \
4          105  Rohan   17   Mumbai    40       52       47   
12         113    Dev   17   Mumbai    35       45       42   
18         119   Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5   
12                  62                     2                      4   
18                  66                     3                      5   

    final_project_score    Average result  
4                    45  46.333333   Pass  
12                   39  40.666667   Pass  
18                   48  46.000000   Pass  


In [42]:
df.to_csv("session4_student_report.csv", index=False)

Homework

In [44]:
average_final = df['final_project_score'].mean()
print(average_final)

73.65


In [45]:
hours_gr_than_8 = df[df['study_hours_per_week'] > 8]
print(hours_gr_than_8)

    student_id    name  age   city  math  science  english  \
1          102    Diya   16  Delhi    91       88       94   
5          106    Sara   16  Delhi    88       93       90   
7          108  Ananya   16  Noida    95       92       89   
9          110    Tara   16  Delhi    83       76       85   
13         114   Priya   16  Delhi    89       86       91   
15         116    Riya   16  Noida    92       90       96   
17         118   Aditi   16  Delhi    80       85       83   

    attendance_percent  study_hours_per_week  assignments_submitted  \
1                   96                    11                     10   
5                   97                    10                     10   
7                   94                    12                     10   
9                   90                     9                      9   
13                  95                    10                     10   
15                  98                    13                     10   
17    

In [48]:
mumbai_avg = df[df["city"] == "Mumbai"]["Average"].mean()
pune_avg = df[df["city"] == "Pune"]["Average"].mean()

print("Mumbai Average:", mumbai_avg)
print("Pune Average:", pune_avg)

Mumbai Average: 56.2
Pune Average: nan


In [49]:
df['performance_level'] = df['Average'].apply(
    lambda x: 'Excellent' if x >= 80
    else 'Good' if x >= 60
    else 'Average' if x >= 40
    else 'Poor'
)

print(df['performance_level'])

0          Good
1     Excellent
2       Average
3          Good
4       Average
5     Excellent
6          Good
7     Excellent
8       Average
9     Excellent
10         Good
11         Good
12      Average
13    Excellent
14      Average
15    Excellent
16         Good
17    Excellent
18      Average
19         Good
Name: performance_level, dtype: object


In [52]:
df[["student_id", "name", "city", "Average", "result", "performance_level"]].to_csv("session4_selected_students.csv", index=False)